name = "AirfoilPrep"
uuid = "008c61af-3522-4e14-81c5-9301d18a9f66"
authors = ["FLOW Lab <aning@byu.edu>"]
version = "2.1.2"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Xfoil = "19641d66-a62d-11e8-2441-8f57a969a9c4"

[compat]
julia = "1"
